#+TITLE: Keyboard Layouts
#+DESCRIPTION: Analysis of the four common keyboard layouts.
#+KEYWORDS: Web, CSS
#+PROPERTY: header-args :eval no-export

#+DATE: [2018-04-05 Thu]

* Creating Keyboard In HTML and CSS
  The following keyboard images are not actually images. They are built using
  =div= elements and CSS grid.  The grid is 29 columns by 5 rows.  Most of the
  =div= elements span two columns.  Each =div= has a column class and a row
  class.  The column that each =div= starts at is calculated in CSS.  The =div=
  elements of class, =col-1=, have a =--column: 1= variable, the =div= elements
  of class, =col-2=, have a =--column: 2= variable, and so on.  Each keyboard
  graphic is contained in a =div= with class QWERTY, Dvorak, Workman, or
  Colemak.
* Counting Gutenberg Data
  I used Awk to find the frequency of characters in 597 text files from a
  [[https://www.gutenberg.org/files/11220/PG2003-08.ISO][Gutenberg Press CD]]. New-lines were counted as a return key presses, and indents
  were counted as TAB characters.  Left and right shift keys were also counted
  separately; capital characters that are typed with the left hand use the right
  shift, and characters typed with the right hand use the left shift.

  The keyboards are colored as heat maps where red characters have the highest
  frequency, blue the least, and green average.  The different keyboard layouts
  have different frequency graphs due to the left and right shift keys being
  included in the frequency count.  The colors maps were generated by linearly
  mapping the numbers 0 through 57 to the H parameter of the HSV color space
  where the minimum H value is 0 and the maximum H value is 241. S and V where
  set to 1, and the resulting HSV values were converted to RGB.
** QWERTY
   [[file:keyboard-layouts/keyboard.html][INSERT QWERTY]]
** Dvorak
   [[file:keyboard-layouts/keyboard.html][INSERT Dvorak]]
** Colemak
   [[file:keyboard-layouts/keyboard.html][INSERT Colemak]]
** Workman
   [[file:keyboard-layouts/keyboard.html][INSERT Workman]]
* Counting Code Files
  I also applied the Awk script to 169102 code files found on my computer.
** QWERTY
   [[file:keyboard-layouts/keyboard.html][INSERT QWERTY code]]
** Dvorak
   [[file:keyboard-layouts/keyboard.html][INSERT Dvorak code]]
** Colemak
   [[file:keyboard-layouts/keyboard.html][INSERT Colemak code]]
** Workman
   [[file:keyboard-layouts/keyboard.html][INSERT Workman code]]
* Awk script                                                       :noexport:
  #+BEGIN_SRC awk
BEGIN {
    FS=""
}
function percent(part) {
    if(TOTAL == 0) {
	return 0
    } else {
	return part * 100 / TOTAL
    }
}

/^\s\s+/ {
    sub(/^\s\s+/, "\t",$0)
}
{
    i = 1
    while(i <= NF) {
	histogram[$i]++
	i++
    }
}
END {
    # qwerty, dvorak, workman, colemak perferred shift
    shift["~"] = "rrrr"
    shift["!"] = "rrrr"
    shift["@"] = "rrrr"
    shift["#"] = "rrrr"
    shift["$"] = "rrrr"
    shift["%"] = "rrrr"
    shift["^"] = "llll"
    shift["&"] = "llll"
    shift["*"] = "llll"
    shift["("] = "llll"
    shift[")"] = "llll"
    shift["_"] = "llll"
    shift["+"] = "llll"
    shift["Q"] = "rrrr"
    shift["W"] = "rlrr"
    shift["E"] = "rrll"
    shift["R"] = "rlrr"
    shift["T"] = "rlrr"
    shift["Y"] = "lrll"
    shift["U"] = "lrll"
    shift["I"] = "lrll"
    shift["O"] = "lrll"
    shift["P"] = "lrlr"
    shift["{"] = "llll"
    shift["}"] = "llll"
    shift["|"] = "llll"
    shift["A"] = "rrrr"
    shift["S"] = "rlrr"
    shift["D"] = "rlrr"
    shift["F"] = "rllr"
    shift["G"] = "rlrr"
    shift["H"] = "llrl"
    shift["J"] = "lrll"
    shift["K"] = "lrll"
    shift["L"] = "llll"
    shift[":"] = "lrll"
    shift["\""] = "lrll"
    shift["Z"] = "rlrr"
    shift["X"] = "rrrr"
    shift["C"] = "rlrr"
    shift["V"] = "rlrr"
    shift["B"] = "rlrr"
    shift["N"] = "llll"
    shift["M"] = "llrl"
    shift["<"] = "lrll"
    shift[">"] = "lrll"
    shift["?"] = "llll"

    # preferred shift frequency
    for(char in shift) {
	if(char in histogram) {
	    if(substr(shift[char],1,1) == "l") {
		qwerty_sl += histogram[char]
	    } else {
		qwerty_sr += histogram[char]
	    }
	    if(substr(shift[char],2,1) == "l") {
		dvorak_sl += histogram[char]
	    } else {
		dvorak_sr += histogram[char]
	    }
	    if(substr(shift[char],3,1) == "l") {
		workman_sl += histogram[char]
	    } else {
		workman_sr += histogram[char]
	    }
	    if(substr(shift[char],4,1) == "l") {
		colemak_sl += histogram[char]
	    } else {
		colemak_sr += histogram[char]
	    }
	}
    }

    # combine shift and non-shift keyboard characters
    combined["q"] = histogram["q"] + histogram["Q"]
    combined["w"] = histogram["w"] + histogram["W"]
    combined["e"] = histogram["e"] + histogram["E"]
    combined["r"] = histogram["r"] + histogram["R"]
    combined["t"] = histogram["t"] + histogram["T"]
    combined["y"] = histogram["y"] + histogram["Y"]
    combined["u"] = histogram["u"] + histogram["U"]
    combined["i"] = histogram["i"] + histogram["I"]
    combined["o"] = histogram["o"] + histogram["O"]
    combined[";"] = histogram[";"] + histogram[":"]
    combined["["] = histogram["["] + histogram["{"]
    combined["]"] = histogram["]"] + histogram["}"]
    combined["\\"] = histogram["\\"] + histogram["|"]
    combined["a"] = histogram["a"] + histogram["A"]
    combined["s"] = histogram["s"] + histogram["S"]
    combined["d"] = histogram["d"] + histogram["D"]
    combined["f"] = histogram["f"] + histogram["F"]
    combined["g"] = histogram["g"] + histogram["G"]
    combined["h"] = histogram["h"] + histogram["H"]
    combined["j"] = histogram["j"] + histogram["J"]
    combined["k"] = histogram["k"] + histogram["K"]
    combined["l"] = histogram["l"] + histogram["L"]
    combined["p"] = histogram["p"] + histogram["P"]
    combined["'"] = histogram["'"] + histogram["\""]
    combined["z"] = histogram["z"] + histogram["Z"]
    combined["x"] = histogram["x"] + histogram["X"]
    combined["c"] = histogram["c"] + histogram["C"]
    combined["v"] = histogram["v"] + histogram["V"]
    combined["b"] = histogram["b"] + histogram["B"]
    combined["n"] = histogram["n"] + histogram["N"]
    combined["m"] = histogram["m"] + histogram["M"]
    combined[","] = histogram[","] + histogram["<"]
    combined["."] = histogram["."] + histogram[">"]
    combined["/"] = histogram["/"] + histogram["?"]
    combined["`"] = histogram["`"] + histogram["~"]
    combined["1"] = histogram["1"] + histogram["!"]
    combined["2"] = histogram["2"] + histogram["@"]
    combined["3"] = histogram["3"] + histogram["#"]
    combined["4"] = histogram["4"] + histogram["$"]
    combined["5"] = histogram["5"] + histogram["%"]
    combined["6"] = histogram["6"] + histogram["^"]
    combined["7"] = histogram["7"] + histogram["&"]
    combined["8"] = histogram["8"] + histogram["*"]
    combined["9"] = histogram["9"] + histogram["("]
    combined["0"] = histogram["0"] + histogram[")"]
    combined["-"] = histogram["-"] + histogram["_"]
    combined["="] = histogram["="] + histogram["+"]
    combined["Space"] = histogram[" "]
    combined["Tab"] = histogram["\t"]

    # number of carriage returns
    combined["Return"] = NR

    # number of shifts
    TOTAL = qwerty_sr + qwerty_sl

    # number of characters
    for(char in combined) {
	TOTAL += combined[char]
    }

    for(char in combined) {
	print combined[char] "\t'"char"'"
    }

    print qwerty_sl "\tqwerty shift_l"
    print qwerty_sr "\tqwerty shift_r"
    print dvorak_sl "\tdvorak shift_l"
    print dvorak_sr "\tdvorak shift_r"
    print workman_sl "\tworkman shift_l"
    print workman_sr "\tworkman shift_r"
    print colemak_sl "\tcolemak shift_l"
    print colemak_sr "\tcolemak shift_r"

    print TOTAL "\tTotal"
}
  #+END_SRC
* data                                                             :noexport:
  597 files from Gutenberg

  #+BEGIN_SRC sh :eval no
find iso -name '*.txt' -exec cat {} \; | awk -f count-characters.awk | sort -n
  #+END_SRC

| '\'             |   0.0020376 |  0 | #0034ff | key_pipe_c        |
| '='             |  0.00361989 |  1 | #0044ff | key_equal_c       |
| '`'             |  0.00582709 |  2 | #0056ff | key_tilde_c       |
| '['             |   0.0285443 |  3 | #0066ff | key_leftsquare_c  |
| ']'             |   0.0291571 |  4 | #0078ff | key_rightsquare_c |
| 'z'             |   0.0581139 |  5 | #0088ff | key_z_c           |
| '/'             |    0.062455 |  6 | #009aff | key_question_c    |
| 'Tab'           |   0.0687153 |  7 | #00aaff | key_tab_c         |
| 'q'             |   0.0958039 |  8 | #00bcff | key_q_c           |
| '6'             |    0.104286 |  9 | #00ccff | key_6_c           |
| '7'             |    0.104639 | 10 | #00ddff | key_7_c           |
| '5'             |    0.106457 | 11 | #00eeff | key_5_c           |
| '4'             |    0.107352 | 12 | #00ffff | key_4_c           |
| 'j'             |    0.115934 | 13 | #00ffee | key_j_c           |
| '3'             |    0.117996 | 14 | #00ffdd | key_3_c           |
| '2'             |    0.124059 | 15 | #00ffcc | key_2_c           |
| '8'             |    0.125874 | 16 | #00ffbc | key_8_c           |
| '9'             |    0.134685 | 17 | #00ffaa | key_9_c           |
| 'x'             |    0.138441 | 18 | #00ff9a | key_x_c           |
| '0'             |    0.156817 | 19 | #00ff88 | key_0_c           |
| '1'             |     0.21564 | 20 | #00ff78 | key_1_c           |
| ';'             |    0.245322 | 21 | #00ff66 | key_colon_c       |
| '-'             |    0.276137 | 22 | #00ff56 | key_underscore_c  |
| '''             |     0.47123 | 23 | #00ff44 | key_quote_c       |
| 'k'             |     0.49377 | 24 | #00ff34 | key_k_c           |
| 'v'             |    0.742596 | 25 | #00ff22 | key_v_c           |
| '.'             |      0.8169 | 26 | #00ff12 | key_period_c      |
| 'b'             |     1.12932 | 27 | #00ff00 | key_b_c           |
| 'p'             |     1.32998 | 28 | #11ff00 | key_p_c           |
| 'y'             |     1.37407 | 29 | #22ff00 | key_y_c           |
| ','             |     1.40693 | 30 | #33ff00 | key_comma_c       |
| 'g'             |     1.40891 | 31 | #44ff00 | key_g_c           |
| dvorak shift_r  |     1.45382 | 32 | #55ff00 |                   |
| colemak shift_r |     1.55325 | 33 | #66ff00 |                   |
| 'w'             |     1.58117 | 34 | #77ff00 | key_w_c           |
| qwerty shift_r  |     1.58993 | 35 | #89ff00 |                   |
| workman shift_l |       1.593 | 36 | #9aff00 |                   |
| workman shift_r |     1.64939 | 37 | #abff00 |                   |
| qwerty shift_l  |     1.65247 | 38 | #bcff00 |                   |
| colemak shift_l |     1.68915 | 39 | #ccff00 |                   |
| 'f'             |     1.75674 | 40 | #ddff00 | key_f_c           |
| dvorak shift_l  |     1.78857 | 41 | #eeff00 |                   |
| 'm'             |     1.92041 | 42 | #ffff00 | key_m_c           |
| 'c'             |     1.93612 | 43 | #ffee00 | key_c_c           |
| 'Return'        |      1.9734 | 44 | #ffdd00 | key_enter_c       |
| 'u'             |     2.11249 | 45 | #ffcc00 | key_u_c           |
| 'l'             |     2.93357 | 46 | #ffbb00 | key_l_c           |
| 'd'             |     3.18385 | 47 | #ffaa00 | key_d_c           |
| 'r'             |     4.45174 | 48 | #ff9900 | key_r_c           |
| 'h'             |     4.66482 | 49 | #ff8800 | key_h_c           |
| 's'             |     4.73394 | 50 | #ff7700 | key_s_c           |
| 'n'             |     5.15294 | 51 | #ff6600 | key_n_c           |
| 'i'             |     5.16111 | 52 | #ff5500 | key_i_c           |
| 'o'             |      5.6658 | 53 | #ff4400 | key_o_c           |
| 'a'             |     5.96746 | 54 | #ff3300 | key_a_c           |
| 't'             |     6.82192 | 55 | #ff2200 | key_t_c           |
| 'e'             |     9.40028 | 56 | #ff1100 | key_e_c           |
| 'Space'         |     15.7382 | 57 | #ff0000 | key_space_c       |
|-----------------+-------------+----+---------+-------------------|
| Total           | 429,819,753 |    |         |                   |

169102 local code files
#+BEGIN_SRC sh :eval no
find . -name '*.el' -o -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" -o -name "*.js" -o -name "*.htm" -o -name "*.html" -o -name "*.css" -o -name "*.php" -o -name "*.py" -exec cat {} \; | awk -f gutenberg/count-characters.awk | sort -n
#+END_SRC

|    149370 | '`'              | key_tilde_c       | #0034ff |
|    168196 | 'z'              | key_z_c           | #0044ff |
|    265459 | 'j'              | key_j_c           | #0056ff |
|    268984 | '/'              | key_question_c    | #0066ff |
|    297379 | '7'              | key_7_c           | #0078ff |
|    335556 | 'q'              | key_q_c           | #0088ff |
|    339963 | '6'              | key_6_c           | #009aff |
|    387585 | '4'              | key_4_c           | #00aaff |
|    421232 | ']'              | key_rightsquare_c | #00bcff |
|    422204 | '['              | key_leftsquare_c  | #00ccff |
|    461489 | '8'              | key_8_c           | #00ddff |
|    495912 | '5'              | key_5_c           | #00eeff |
|    536055 | '\'              | key_pipe_c        | #00ffff |
|    669431 | '2'              | key_2_c           | #00ffee |
|    677880 | 'k'              | key_k_c           | #00ffdd |
|    723600 | 'x'              | key_x_c           | #00ffcc |
|    735588 | '1'              | key_1_c           | #00ffbc |
|    746078 | 'w'              | key_w_c           | #00ffaa |
|    839529 | 'v'              | key_v_c           | #00ff9a |
|    998380 | '3'              | key_3_c           | #00ff88 |
|   1214802 | 'y'              | key_y_c           | #00ff78 |
|   1219578 | '='              | key_equal_c       | #00ff66 |
|   1375621 | 'b'              | key_b_c           | #00ff56 |
|   1427412 | ';'              | key_colon_c       | #00ff44 |
|   1721232 | '9'              | key_9_c           | #00ff34 |
|   2109710 | 'g'              | key_g_c           | #00ff22 |
|   2111400 | 'h'              | key_h_c           | #00ff12 |
|   2306294 | '.'              | key_period_c      | #00ff00 |
|   2306833 | '0'              | key_0_c           | #11ff00 |
|   2761457 | 'm'              | key_m_c           | #22ff00 |
|   2866217 | ','              | key_comma_c       | #33ff00 |
|   3021589 | '-'              | key_underscore_c  | #44ff00 |
|   3112223 | 'f'              | key_f_c           | #55ff00 |
|   3175350 | 'Tab'            | key_tab_c         | #66ff00 |
|   3277584 | 'p'              | key_p_c           | #77ff00 |
|   3651005 | 'c'              | key_c_c           | #89ff00 |
|   3663287 | '''              | key_quote_c       | #9aff00 |
|   3674319 | 'd'              | key_d_c           | #abff00 |
|   3743263 | 'u'              | key_u_c           | #bcff00 |
|   4347841 | 'Return'         | key_enter_c       | #ccff00 |
|   4762964 | 'l'              | key_l_c           | #ddff00 |
|   5052242 | workman shift_r  | workman shift_r   | #eeff00 |
|   5343530 | colemak shift_r  | colemak shift_r   | #ffff00 |
|   5680217 | qwerty shift_r   | qwerty shift_r    | #ffee00 |
|   6357379 | 'n'              | key_n_c           | #ffdd00 |
|   6370750 | 'o'              | key_o_c           | #ffcc00 |
|   6424744 | 'i'              | key_i_c           | #ffbb00 |
|   6568649 | dvorak shift_r   | dvorak shift_r    | #ffaa00 |
|   6890445 | 'r'              | key_r_c           | #ff9900 |
|   6922569 | 'a'              | key_a_c           | #ff8800 |
|   7681710 | 's'              | key_s_c           | #ff7700 |
|   8760204 | 't'              | key_t_c           | #ff6600 |
|  10920623 | dvorak shift_l   | dvorak shift_l    | #ff5500 |
|  11809055 | qwerty shift_l   | qwerty shift_l    | #ff4400 |
|  12145742 | fcolemak shift_l | fcolemak shift_l  | #ff3300 |
|  12146297 | 'Space'          | key_space_c       | #ff2200 |
|  12437030 | workman shift_l  | workman shift_l   | #ff1100 |
|  13330965 | 'e'              | key_e_c           | #ff0000 |
|-----------+------------------+-------------------+---------|
| 160164186 | Total            |                   |         |

